---
- name: run the main role
  hosts: all
  pre_tasks:
    - name: update repositories cache
      apt:
        update_cache: yes
    - package: name={{ item }} state=latest
      with_items:
        - curl
        - jq
        - iproute
        - rsyslog
        - ca-certificates
        - sudo
        - python-apt
        - software-properties-common
        - tar
        - unzip
        - bzip2
        - gzip
        - git
  vars:
    es_api_host: "0.0.0.0"
    es_instance_name: "node1"
    es_enable_xpack: true
    es_xpack_features: ["monitoring"]
    prometheus_exporter_name: node_exporter
    prometheus_exporter_version: 0.16.0
  roles:
    - role: ansible-elasticsearch
    - role: entercloudsuite.consul
      consul_version: 1.2.3
      consul_packer_provision: true
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "K8n07GA/ZoANSmJ5zkvgOg=="
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
    - role: entercloudsuite.kibana
      kibana_server_port: 5601
      kibana_server_host: "0.0.0.0"
    - role: entercloudsuite.prometheus-exporter
      prometheus_exporter_name: node_exporter
      prometheus_exporter_version: 0.16.0
    - role: entercloudsuite.prometheus-exporter
      prometheus_exporter_name: elasticsearch_exporter
      prometheus_exporter_version: 1.0.2
      prometheus_github_username: justwatchcom
      prometheus_exporter_config_flags:
        '-es.uri': 'http://localhost:9200'
- name: prepare virtualenv
  hosts: all
  tasks:
    - name: create var project path
      set_fact:
        script_path: /usr/src/cloud
    - name: install requirements
      package: name="{{ item }}"
      with_items:
        - libffi-dev
        - libssl-dev
        - python-minimal
        - python-pip
        - virtualenv
    - name: create directory
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ script_path }}"
        - "{{ script_path }}/roles"
    - name: create requirements.txt
      copy:
        content: |
          ansible==2.6.2
          asn1crypto==0.23.0
          bcrypt==3.1.4
          cffi==1.11.2
          cryptography==2.1.3
          enum34==1.1.6
          idna==2.6
          ipaddress==1.0.18
          Jinja2==2.10
          MarkupSafe==1.0
          paramiko==2.4.0
          pyasn1==0.3.7
          pycparser==2.18
          pycrypto==2.6.1
          PyNaCl==1.2.0
          PyYAML==3.12
          six==1.11.0
          jmespath==0.9.3
        dest: "{{ script_path }}/requirements.txt"
        remote_src: yes
    - name: create requirements.yml
      copy:
        content: |
          - src: "https://github.com/{{ lookup('env','TRAVIS_REPO_SLUG') }}"
            version: "{{ lookup('env','TRAVIS_COMMIT') }}"
          - src: entercloudsuite.consul
            version: 1.0.1
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
    - name: create requirements.yml
      copy:
        content: |
          - src: "https://github.com/{{ lookup('env','TRAVIS_PULL_REQUEST_SLUG') }}"
            version: "{{ lookup('env','TRAVIS_PULL_REQUEST_SHA') }}"
          - src: entercloudsuite.consul
            version: 1.0.1
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
      when: lookup('env','TRAVIS_PULL_REQUEST_SLUG') != ""
    - name: install python requirements
      pip:
        requirements: "{{ script_path }}/requirements.txt"
        virtualenv: "{{ script_path }}/venv"
    - name: install ansible roles
      shell: source {{ script_path }}/venv/bin/activate && ansible-galaxy install -f -p roles -r requirements.yml
      args:
        chdir: "{{ script_path }}"
        executable: /bin/bash
