---
- name: run the main role
  hosts: all
  vars:
    es_api_host: "0.0.0.0"
  roles:
    - role: ansible-elasticsearch
      es_instance_name: "node1"
      es_enable_xpack: false
    - role: entercloudsuite.kibana
      kibana_server_port: 5601
      kibana_server_host: "0.0.0.0"
    - role: entercloudsuite.prometheus-exporter
      prometheus_exporter_name: node_exporter
      prometheus_exporter_version: 0.16.0
