---
- name: run the main role 
  hosts: all
  roles:
    - role: elastic.elasticsearch
      es_instance_name: "node1"
      es_enable_xpack: false
    - role: geerlingguy.kibana
      kibana_server_port: 5601
      kibana_server_host: "0.0.0.0"
